# Generated by Django 5.1.4 on 2024-12-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentnotification',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
